### ISSUE TITLE
Remove dependency on org.slf4j/slf4j-log4j12?

### ISSUE THREAD

**Issue by rborer** [mpenet/sextant#1]
[`project.clj` have a dependency on `slf4j-log4j12`](https://github.com/mpenet/sextant/blob/daadc166564d8333c92511cdabc0232aa97fa3ee/project.clj#L6). This dependency is superfluous as it is the binding between slf4j logging API and Log4j 1.2 logger. Thus it forces projects using this dependency to either use Log4j 1.2 or exclude this dependency.

I believe it can safely be removed (or moved into the `:dev` profile to remove some warnings at compile time).

If you agree I can make a PR 😄 .

**Comment by mpenet** [comment]
Pr welcomed
